## create a new branch with the name fix
name: Test Workflow

on:
  push:
    branches:
      - 'fix*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Run a simple command
        run: echo "Hello, World!"
