# Description: Automatically open a pull request when a new branch is created.
name: Auto Open Pull Request

on:
  create:
    branches:
      - 'feat/*'
      - 'fix/*'
      - 'hotfix/*'

permissions:
  pull-requests: write

jobs:
  open-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the first commit message
        id: get_commit
        run: |
          # GET the first commit hash
          FIRST_COMMIT=$(git rev-list --max-parents=0 HEAD)
          FIRST_COMMIT_MSG=$(git log --format=%B -n 1 $FIRST_COMMIT)
          echo "first_commit_message=${FIRST_COMMIT_MSG}" >> $GITHUB_ENV

      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: '${{ env.first_commit_message }}'
          body: |
            $(cat PULL_REQUEST_TEMPLATE/default.md)
          branch: ${{ github.ref }}
          base: main
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Assign PR to author
        run: |
          # Get the PR number
          PR_NUMBER=$(echo "${{ github.event.pull_request.number }}")
          # Assign the PR to the author
          curl -s -X POST https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/assignees \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"assignees\": [\"${{ github.actor }}\"]}"

      - name: Add label to PR
        run: |
          # Get the PR number
          PR_NUMBER=$(echo "${{ github.event.pull_request.number }}")
          # Add the 'review' label to the PR
          curl -s -X POST https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/labels \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"labels\": [\"waiting review\"]}"
