# Description: Automatically open a pull request when a new branch is created. 1234567890
name: Auto Open Pull Request

on:
  create:
    branches:
      - 'feat/*'
      - 'fix/*'
      - 'hotfix/*'

permissions:
  pull-requests: write

jobs:
  open-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: 'Auto PR: ${{ github.ref }}'
          body: 'This is an automated pull request created when a new branch was detected.'
          branch: ${{ github.ref }}
          base: main
          draft: true 
          token: ${{ secrets.GITHUB_TOKEN }}
